import { Inter } from "next/font/google";
import "./globals.css";
import TopHeader from "../headers/TopHeader"
import MiddleHeader from "../headers/MiddleHeader"
import BottomHeader from "../headers/BottomHeader"
import Foter from "../components/Foter"
import { ToastContainer, toast } from 'react-toastify';
import ProviderLayout from "../components/ui/ProviderLayout"
import 'react-toastify/dist/ReactToastify.css';


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <ProviderLayout>
            <TopHeader/>
            <MiddleHeader/> 
            <BottomHeader/>
              {children}
              <ToastContainer autoClose={1000} />
            <Foter/>
          </ProviderLayout>
        </body>
    </html>
  );
}
